### ISSUE TITLE
Удаляется из svg тег <filter>

### ISSUE THREAD

**Issue by p4rs1f41** [beliarh/project-template#2]
В каком пакете обрабатывается и где посмотреть настройки?

**Comment by p4rs1f41** [comment]
При сшивании в sprite.svg. Удаляются теги filter.

**Comment by beliarh** [comment]
Можно получить исходный svg-файл с фильтром?

**Comment by p4rs1f41** [comment]
[Ссылка на файл](http://alexnab.ru/test6/images/sprites/svg/s1__img1.svg)
Пропадает белое размытие ракеты если вставлять через pug миксин +svg()

**Comment by beliarh** [comment]
Проблема не в оптимизации svg. `<filter>` не удаляется.
Это баг движка Chromium (https://bugs.chromium.org/p/chromium/issues/detail?id=109212).
В Firefox фильтр работает и корректно отображается.
Как можно решить проблему:
- либо перенести файл в `src/images` и работать как с обычной картинкой (через `<img>` или `background`)
- либо подключить иконку непосредственно в pug:
```pug
// Вместо подключения через <svg><use/></svg>:
+svg("s1__img1")

// Подключать напрямую:
include images/sprites/s1__img1.svg
```
